### PR TITLE
Merging 'ObjectTracking' into 'main'

### PR DESCRIPTION
**Pull request by bhageneder**
Updated Detector.py Detector class to include object tracking and reconfigured some debug prints. Added a .gitignore file to untrack __pycache__. Need to delete pycache instances already in project.

### CODE REVIEW

**Comment by bhageneder** [comment]
DO NOT DELETE THE BRANCH ONCE MERGED. Make sure to keep branch alive as I will be continuing to update object tracking via this branch.

**Review by Mitchell-Conrad-20 — APPROVED** [review]
I am okay with this. Just curious why you don't just delete and make a new branch once this is merged in? Deleting the branch should be standard practice, unless there is a reason.

**Comment by bhageneder** [comment]
The feature development for this isn't finished, however, there are changes that should be put into main (specifically the basic object tracking and updated git ignore) which would make it better for further development on any branch

**Comment by Mitchell-Conrad-20** [comment]
Makes sense. I feel like it would be better to make a new branch with a title that specifies what you will be adding in.

**Comment by bhageneder** [comment]
That's tedious. The additions would be in the commit messages and can be added to merge descriptions.

**Pull request closed without merging**
