### PR TITLE
Updating SIMDEV with Dev

### PR DESCRIPTION
**Pull request by bhageneder**
Updating the file structure and code changes of Dev into SIMDEV as it is needed for the controller.
DO NOT DELETE EITHER BRANCH AFTER MERGE.

### CODE REVIEW

**Comment by Mitchell-Conrad-20** [comment]
what is this

**Comment by bhageneder** [comment]
> what is this
Updating the file structure and code changes of Dev by merging them into SIMDEV as it is needed for the controller.

**Comment by Mitchell-Conrad-20** [comment]
> > what is this
> > Updating the file structure and code changes of Dev by merging them into SIMDEV as it is needed for the controller.

I read that. I'm wondering what this is, as in, why does every file have diff when we already did this

**Review by Mitchell-Conrad-20 — CHANGES_REQUESTED** [review]
Merge other direction

**Comment by bhageneder** [comment]
Why would it be the other direction? The changes in SIMDEV aren't complete and shouldn't be merged into DEV yet but I need the repo restructure changes in SIMDEV

**Pull request closed without merging**
